[0m04:10:57.435434 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f0b5daf2630>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f0b5c82bc80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f0b5cad4fe0>]}


============================== 04:10:57.443781 | fdd45a81-d201-48ed-9aa6-394a0904ee1e ==============================
[0m04:10:57.443781 [info ] [MainThread]: Running with dbt=1.9.4
[0m04:10:57.445448 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/opt/airflow/dbt_project', 'fail_fast': 'False', 'warn_error': 'None', 'log_path': 'logs', 'debug': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'invocation_command': 'dbt run', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m04:10:57.447272 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /opt/airflow/dbt_project/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m04:10:57.449047 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.073150456, "process_in_blocks": "0", "process_kernel_time": 0.16112, "process_mem_max_rss": "97828", "process_out_blocks": "0", "process_user_time": 1.832743}
[0m04:10:57.450372 [debug] [MainThread]: Command `dbt run` failed at 04:10:57.450231 after 0.07 seconds
[0m04:10:57.451494 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f0b5e57a7e0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f0b5daf2630>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f0b5c7732c0>]}
[0m04:10:57.452510 [debug] [MainThread]: Flushing usage events
[0m04:10:58.013329 [debug] [MainThread]: An error was encountered while trying to flush usage events
