[2025-05-07T09:49:21.636+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-05-07T09:49:21.805+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_etl_dag.run_dbt manual__2025-05-07T09:49:14.561344+00:00 [queued]>
[2025-05-07T09:49:21.873+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_etl_dag.run_dbt manual__2025-05-07T09:49:14.561344+00:00 [queued]>
[2025-05-07T09:49:21.880+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-05-07T09:49:22.004+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): run_dbt> on 2025-05-07 09:49:14.561344+00:00
[2025-05-07T09:49:22.052+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=660) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-05-07T09:49:22.057+0000] {standard_task_runner.py:63} INFO - Started process 665 to run task
[2025-05-07T09:49:22.050+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'weather_etl_dag', 'run_dbt', 'manual__2025-05-07T09:49:14.561344+00:00', '--job-id', '198', '--raw', '--subdir', 'DAGS_FOLDER/weather_etl_dag.py', '--cfg-path', '/tmp/tmpq1r81ag_']
[2025-05-07T09:49:22.062+0000] {standard_task_runner.py:91} INFO - Job 198: Subtask run_dbt
[2025-05-07T09:49:22.135+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-05-07T09:49:22.427+0000] {task_command.py:426} INFO - Running <TaskInstance: weather_etl_dag.run_dbt manual__2025-05-07T09:49:14.561344+00:00 [running]> on host a438d0b68a5b
[2025-05-07T09:49:22.969+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='weather_etl_dag' AIRFLOW_CTX_TASK_ID='run_dbt' AIRFLOW_CTX_EXECUTION_DATE='2025-05-07T09:49:14.561344+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-07T09:49:14.561344+00:00'
[2025-05-07T09:49:22.973+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-05-07T09:49:26.370+0000] {local_task_job_runner.py:124} ERROR - Received SIGTERM. Terminating subprocesses
[2025-05-07T09:49:26.500+0000] {process_utils.py:132} INFO - Sending 15 to group 665. PIDs of all processes in the group: [668, 665]
[2025-05-07T09:49:26.517+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 665
[2025-05-07T09:49:26.527+0000] {taskinstance.py:2611} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-05-07T09:49:26.539+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-05-07T09:49:26.541+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=668, status='terminated', started='09:49:23') (668) terminated with exit code None
[2025-05-07T09:49:26.670+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/weather_etl_dag.py", line 10, in run_dbt
    subprocess.run(['dbt', 'run'], check=True, cwd='/opt/airflow/dags/dbt_project')
  File "/usr/local/lib/python3.12/subprocess.py", line 550, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/subprocess.py", line 1201, in communicate
    self.wait()
  File "/usr/local/lib/python3.12/subprocess.py", line 1264, in wait
    return self._wait(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/subprocess.py", line 2053, in _wait
    (pid, sts) = self._try_wait(0)
                 ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/subprocess.py", line 2011, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2613, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2025-05-07T09:49:27.095+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=weather_etl_dag, task_id=run_dbt, run_id=manual__2025-05-07T09:49:14.561344+00:00, execution_date=20250507T094914, start_date=20250507T094921, end_date=20250507T094927
[2025-05-07T09:49:27.872+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=665, status='terminated', exitcode=2, started='09:49:21') (665) terminated with exit code 2
[2025-05-07T09:49:27.875+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 143
[2025-05-07T09:49:28.033+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-07T09:49:28.135+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
