[2025-05-07T03:37:55.025+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-05-07T03:37:55.190+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_etl_dag.fetch_weather scheduled__2025-05-06T22:00:00+00:00 [queued]>
[2025-05-07T03:37:55.243+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_etl_dag.fetch_weather scheduled__2025-05-06T22:00:00+00:00 [queued]>
[2025-05-07T03:37:55.247+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 1
[2025-05-07T03:37:55.309+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): fetch_weather> on 2025-05-06 22:00:00+00:00
[2025-05-07T03:37:55.335+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=165) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-05-07T03:37:55.333+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'weather_etl_dag', 'fetch_weather', 'scheduled__2025-05-06T22:00:00+00:00', '--job-id', '152', '--raw', '--subdir', 'DAGS_FOLDER/weather_etl_dag.py', '--cfg-path', '/tmp/tmpwpaffby1']
[2025-05-07T03:37:55.340+0000] {standard_task_runner.py:63} INFO - Started process 183 to run task
[2025-05-07T03:37:55.340+0000] {standard_task_runner.py:91} INFO - Job 152: Subtask fetch_weather
[2025-05-07T03:37:55.404+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-05-07T03:37:55.619+0000] {task_command.py:426} INFO - Running <TaskInstance: weather_etl_dag.fetch_weather scheduled__2025-05-06T22:00:00+00:00 [running]> on host 5e7ac55cd0dc
[2025-05-07T03:37:58.084+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='weather_etl_dag' AIRFLOW_CTX_TASK_ID='fetch_weather' AIRFLOW_CTX_EXECUTION_DATE='2025-05-06T22:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-06T22:00:00+00:00'
[2025-05-07T03:37:58.086+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-05-07T03:37:59.162+0000] {logging_mixin.py:188} INFO - Unexpected error: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "pg_type_typname_nsp_index"
DETAIL:  Key (typname, typnamespace)=(stg_weather_raw, 2200) already exists.

[SQL: 
CREATE TABLE stg_weather_raw (
	city TEXT, 
	country TEXT, 
	latitude FLOAT(53), 
	longitude FLOAT(53), 
	date_time TEXT, 
	temperature FLOAT(53), 
	pressure BIGINT, 
	humidity BIGINT, 
	weather_main TEXT, 
	weather_description TEXT
)

]
(Background on this error at: https://sqlalche.me/e/14/gkpj)
[2025-05-07T03:37:59.164+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-05-07T03:37:59.166+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-05-07T03:37:59.195+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=weather_etl_dag, task_id=fetch_weather, run_id=scheduled__2025-05-06T22:00:00+00:00, execution_date=20250506T220000, start_date=20250507T033755, end_date=20250507T033759
[2025-05-07T03:37:59.277+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-05-07T03:37:59.341+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-05-07T03:37:59.350+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
